# Step 1: Build 단계
FROM gradle:8.2.1-jdk17 AS build

# Step 2: 작업 디렉토리 설정
WORKDIR /app

# Step 3: 프로젝트 파일 복사
COPY . .

# Step 4: Gradle을 이용하여 애플리케이션 빌드
RUN gradle build --no-daemon

# Step 5: 실제 이미지 빌드 단계
FROM openjdk:17-jdk-alpine

# Step 6: 작업 디렉토리 설정
WORKDIR /app

# Step 7: 빌드 단계에서 생성된 JAR 파일 복사
COPY --from=build /app/build/libs/helloworld-0.0.1-SNAPSHOT.jar /app/app.jar

# Step 8: 애플리케이션 실행
ENTRYPOINT ["java", "-jar", "/app/app.jar"]